[package]
name        = "saa-wasm-protos"
description = "Procedural macros of of cw-auth"
edition     = { workspace = true }
authors     = { workspace = true }
license     = { workspace = true }
repository  = { workspace = true }
version     = "0.1.0-alpha.1"

[lib]
proc-macro = true

[dependencies.proc-macro2]
version = "1"

[dependencies.quote]
version = "1"

[dependencies.syn]
version = "1"
features = [
    "full",
    "printing",
    "extra-traits",
]
