[package]
name        = "saa-wasm"
description = "Authentication library for smart accounts of CosmWasm"
edition     = { workspace = true }
authors     = { workspace = true }
version     = { workspace = true }
license     = { workspace = true }
readme      = { workspace = true }
repository  = { workspace = true }


[lib]
name        =  "saa_wasm"
path        =  "src/lib.rs"
crate-type  =  ["cdylib", "rlib"]


[dependencies]
smart-account-auth      = { workspace = true }
saa-schema              = { workspace = true }
# saa-common              = { workspace = true }
types                   = { workspace = true }

[features]
default      =   ["cosmwasm_v1", "session"]
cosmwasm_v1  =   ["types/cosmwasm_v1"]
cosmwasm     =   ["types/cosmwasm"]
session      =   ["types/session"]

utils        =   ["smart-account-auth/utils"]
multi        =   [ ]
signed       =   []
types        =   [ ]